name: Container image build and push, update flux config

on:
  workflow_dispatch:
    inputs:
      no-build:
        description: "Use an existing image instead of building a new"
        required: false
        type: choice
        options:
          - true
          - false
        default: "false"

      no-build-tag:
        description: "Existing image tag to use, e.g. '03-10-2022.210'"
        required: false

  pull_request:
    branches:
      - main
    paths:
      - "src/**.cs"
      - "src/**.csproj"
  push:
    branches:
      - main
    paths:
      - "src/**.cs"
      - "src/**.csproj"

jobs:

  dev:
    uses: miljodir/cp-workflow-templates/.github/workflows/acr.yaml@acr/v1
    secrets: inherit
    with:
      environment: dev
      image-name: testteam1/testapp1
      build-path: "./src/aspnetapp"
      dockerfile-path: ./src/aspnetapp/Dockerfile
      no-push: ${{github.event_name == 'pull_request' && true || false}}

      k8s-repo: "wl-testteam1"
      k8s-deploymentfile: "fluxcd/dev/deployment.yaml"
      run-image-scan: "false"
      no-build: ${{ github.event.inputs.no-build }}
      no-build-tag: ${{ github.event.inputs.no-build-tag }}
      build-arg: |
        input=output
        TARGETARCH=x64

  test:
    if: ${{ always() && !cancelled() && github.event_name != 'pull_request' }}
    needs: [dev]
    uses: miljodir/cp-workflow-templates/.github/workflows/acr.yaml@acr/v1
    secrets: inherit
    with:
      environment: test
      image-name: testteam1/testapp1

      k8s-repo: "wl-testteam1"
      k8s-deploymentfile: "fluxcd/test/deployment.yaml"
      run-image-scan: "false"
      no-build: "true"
      no-build-tag: ${{ github.event.inputs.no-build-tag || needs.dev.outputs.image-tag }}


  production:
    if: ${{ always() && !cancelled() && github.event_name != 'pull_request' }}
    needs: [build]
    uses: miljodir/cp-workflow-templates/.github/workflows/acr.yaml@acr/v1
    secrets: inherit
    with:
      environment: production
      image-name: testteam1/testapp1

      k8s-repo: "wl-testteam1"
      k8s-deploymentfile: "fluxcd/prod/deployment.yaml"
      run-image-scan: "false"
      no-build: "true"
      no-build-tag: ${{ github.event.inputs.no-build-tag || needs.build.outputs.image-tag }}
