name: (Dev) Terraform Plan & Apply
on:
  push:
    branches:
      - $default-branch
    paths:
      - platform/dev/**
  pull_request:
    branches:
      - $default-branch
    paths:
      - platform/dev/**

jobs:
  plan:
    if: "${{ github.event_name == 'pull_request' }}"
    uses: miljodir/cp-workflow-templates/.github/workflows/tf-plan.yaml@tf-plan/v2
    with:
      environment: dev
      tfDocsDirectories: "./platform, ./modules"
  secrets: inherit

  apply:
    if: "${{ github.ref == 'refs/heads/main' && github.event_name == 'push'}}"
    uses: miljodir/cp-workflow-templates/.github/workflows/tf-apply.yaml@tf-apply/v2
    with:
      environment: dev
    secrets: inherit
